In [40]:
import pandas as pd

wb_data = pd.read_csv(r"C:\Users\saura\OneDrive\Desktop\Strait Times\Data\Worldwide\World_Data.csv")

In [41]:
wb_data.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,ABW,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,25.246212,25.022278,25.915055,25.746908,28.149710,28.989170,28.705923,28.771570,29.274564,30.128447
2,Afghanistan,AFG,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,27.710843,27.710843,27.710843,27.710843,27.710843,27.710843,27.710843,NaN,27.868852,27.016129
3,Africa Western and Central,AFW,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,11.859086,13.643235,14.705882,15.614157,15.084915,14.843750,15.279107,15.318471,15.398773,16.345271
4,Angola,AGO,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.181818,34.090909,34.090909,36.818182,36.818182,36.818182,30.454545,30.454545,30.000000,30.000000

In [42]:
sg_data = pd.read_csv(r"C:\Users\saura\OneDrive\Desktop\Strait Times\Data\SG\seatsByWomen.csv")

sg_data.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2014,2015,2016,2017,2018,2019,Country Name,Country Code,Indicator Name,Indicator Code
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Aruba,ABW,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.7,27.7,27.7,27.7,27.7,27.87,Afghanistan,AFG,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.8,36.8,36.8,38.2,30.5,30.00,Angola,AGO,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,20.7,22.9,27.9,27.9,29.51,Albania,ALB,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,50.0,39.3,32.1,32.1,32.1,50.00,Andorra,AND,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS

In [43]:
world_distribution = pd.read_csv(r"C:\Users\saura\OneDrive\Desktop\Strait Times\Data\SG\seatsByWomen_Cleaned-Wrangled.csv")

world_distribution

,Country Name,1999,2000,2001,2002,2003,2004,2005,2006,2007,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,12.5,14.8,15.4,16.7,16.7,17.4,19.3,19.8,20.2,...,25.2,25.0,25.9,25.7,28.1,29.0,28.7,28.8,29.3,30.1
2,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,27.3,27.3,27.7,...,27.7,27.7,27.7,27.7,27.7,27.7,27.7,27.7,27.9,27.0
3,Africa Western and Central,NaN,6.8,7.4,7.9,9.0,10.1,10.7,11.2,12.3,...,11.9,13.6,14.7,15.6,15.1,14.8,15.3,15.3,15.4,16.3
4,Angola,15.5,15.5,15.5,15.5,15.5,15.0,15.0,15.0,15.0,...,38.2,34.1,34.1,36.8,36.8,36.8,38.2,30.5,30.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,"Yemen, Rep.",0.7,0.7,0.7,0.7,0.3,0.3,0.3,0.3,0.3,...,0.3,0.3,0.3,0.3,0.0,0.0,0.0,0.0,0.3,0.3
263,South Africa,30.0,29.8,29.8,29.8,29.8,32.8,32.8,32.8,33.0,...,42.3,42.3,42.3,41.5,42.0,41.8,42.0,42.3,45.7,46.8
264,Zambia,10.1,10.1,10.1,12.0,12.0,12.0,12.7,14.6,15.2,...,11.5,11.5,11.5,10.8,12.7,18.0,18.0,18.0,18.0,16.8
265,Zimbabwe,14.0,9.3,10.0,10.0,10.0,10.0,16.0,16.7,16.0,...,15.0,15.0,31.5,31.5,31.5,31.5,32.6,31.5,31.9,31.9

In [44]:
pd.set_option('display.max_rows', df.shape[0]+1)

df = pd.read_csv(r"C:\Users\saura\OneDrive\Desktop\Strait Times\Data\heatmap.csv")

df

                                          Country Name  Percentage
0                          Africa Eastern and Southern        30.1
1                                          Afghanistan        27.0
2                           Africa Western and Central        16.3
3                                               Angola        30.0
4                                              Albania        29.5
5                                              Andorra        46.4
6                                           Arab World        19.5
7                                 United Arab Emirates        50.0
8                                            Argentina        40.9
9                                              Armenia        23.5
10                                 Antigua and Barbuda        11.1
11                                           Australia        30.5
12                                             Austria        39.3
13                                          Azerbaijan        17.4
14                                             Burundi        38.2
15                                             Belgium        41.3
16                                               Benin         7.2
17                                        Burkina Faso         6.3
18                                          Bangladesh        20.9
19                                            Bulgaria        26.7
20                                             Bahrain        15.0
21                                        Bahamas, The        12.8
22                              Bosnia and Herzegovina        26.2
23                                             Belarus        40.0
24                                              Belize         9.7
25                                             Bolivia        46.2
26                                              Brazil        14.6
27                                            Barbados        20.0
28                                   Brunei Darussalam         9.1
29                                              Bhutan        14.9
30                                            Botswana        10.8
31                            Central African Republic         8.6
32                                              Canada        29.0
33                      Central Europe and the Baltics        25.0
34                                         Switzerland        41.5
35                                               Chile        22.6
36                                               China        24.9
37                                       Cote d'Ivoire        11.4
38                                            Cameroon        33.9
39                                    Congo, Dem. Rep.        12.8
40                                         Congo, Rep.        11.3
41                                            Colombia        18.3
42                                             Comoros        16.7
43                                          Cabo Verde        25.0
44                                          Costa Rica        45.6
45                              Caribbean small states        25.5
46                                                Cuba        53.2
47                                              Cyprus        19.6
48                                      Czech Republic        22.5
49                                             Germany        31.2
50                                            Djibouti        26.2
51                                            Dominica        34.4
52                                             Denmark        39.7
53                                  Dominican Republic        27.9
54                                             Algeria        25.8
55         East Asia & Pacific (excluding high income)        21.5
56                          Early-demographic dividend        24.5
57                                 East Asia & Pacific        21.3
58       Europe & Central Asia (excluding high income)        23.6
59                               Europe & Central Asia        30.3
60                                             Ecuador        39.4
61                                    Egypt, Arab Rep.        27.4
62                                           Euro area        33.9
63                                               Spain        44.0
64                                             Estonia        28.7
65                                            Ethiopia        38.8
66                                      European Union        32.4
67            Fragile and conflict affected situations        20.6
68                                             Finland        46.0
69                                                Fiji        19.6
70                                              France        39.5
71                               Micronesia, Fed. Sts.         0.0
72                                               Gabon        14.8
73                                      United Kingdom        33.8
74                                             Georgia        20.7
75                                               Ghana        13.1
76                                              Guinea        16.7
77                                         Gambia, The         8.6
78                                       Guinea-Bissau        13.7
79                                   Equatorial Guinea        21.0
80                                              Greece        21.7
81                                             Grenada        46.7
82                                           Guatemala        19.4
83                                              Guyana        35.7
84                                         High income        30.3
85                                            Honduras        21.1
86              Heavily indebted poor countries (HIPC)        25.2
87                                             Croatia        31.1
88                                             Hungary        12.1
89                                           IBRD only        24.3
90                                    IDA & IBRD total        23.5
91                                           IDA total        22.3
92                                           IDA blend        21.1
93                                           Indonesia        20.3
94                                            IDA only        22.6
95                                               India        14.4
96                                             Ireland        22.5
97                                  Iran, Islamic Rep.         5.6
98                                                Iraq        26.4
99                                             Iceland        38.1
100                                             Israel        27.5
101                                              Italy        35.7
102                                            Jamaica        28.6
103                                             Jordan        11.5
104                                              Japan         9.9
105                                         Kazakhstan        27.1
106                                              Kenya        21.8
107                                    Kyrgyz Republic        16.5
108                                           Cambodia        20.0
109                                           Kiribati         8.9
110                                St. Kitts and Nevis        25.0
111                                        Korea, Rep.        19.0
112                                             Kuwait         6.3
113  Latin America & Caribbean (excluding high income)        34.5
114                                            Lao PDR        27.5
115                                            Lebanon         4.7
116                                            Liberia        12.3
117                                              Libya        16.0
118                                          St. Lucia        16.7
119                          Latin America & Caribbean        32.8
120       Least developed countries: UN classification        24.2
121                                         Low income        22.5
122                                      Liechtenstein        12.0
123                                          Sri Lanka         5.4
124                                Lower middle income        21.8
125                                Low & middle income        23.9
126                                            Lesotho        23.3
127                          Late-demographic dividend        22.2
128                                          Lithuania        27.0
129                                         Luxembourg        30.0
130                                             Latvia        30.0
131                                            Morocco        20.5
132                                             Monaco        33.3
133                                            Moldova        24.8
134                                         Madagascar        17.9
135                                           Maldives         4.6
136                         Middle East & North Africa        18.3
137                                             Mexico        48.2
138                                   Marshall Islands         6.1
139                                      Middle income        24.3
140                                    North Macedonia        39.2
141                                               Mali        27.9
142                                              Malta        13.4
143                                            Myanmar        16.8
144  Middle East & North Africa (excluding high inc...        18.4
145                                         Montenegro        22.2
146                                           Mongolia        17.3
147                                         Mozambique        42.4
148                                         Mauritania        20.3
149                                          Mauritius        20.0
150                                             Malawi        22.9
151                                           Malaysia        14.9
152                                      North America        28.1
153                                            Namibia        43.3
154                                              Niger        17.0
155                                            Nigeria         7.2
156                                          Nicaragua        47.3
157                                        Netherlands        33.3
158                                             Norway        41.4
159                                              Nepal        32.7
160                                              Nauru        10.5
161                                        New Zealand        48.3
162                                       OECD members        31.5
163                                               Oman         2.3
164                                 Other small states        20.9
165                                           Pakistan        20.2
166                                             Panama        22.5
167                                               Peru        26.2
168                                        Philippines        28.0
169                                              Palau         6.3
170                                   Papua New Guinea         0.0
171                                             Poland        28.7
172                           Pre-demographic dividend        22.9
173                          Korea, Dem. Peopleâ€™s Rep.        17.6
174                                           Portugal        40.0
175                                           Paraguay        16.3
176                        Pacific island small states         8.1
177                          Post-demographic dividend        32.9
178                                              Qatar         9.8
179                                            Romania        21.9
180                                 Russian Federation        15.8
181                                             Rwanda        61.3
182                                         South Asia        18.9
183                                       Saudi Arabia        19.9
184                                            Senegal        43.0
185                                          Singapore        29.5
186                                    Solomon Islands         6.4
187                                       Sierra Leone        12.3
188                                        El Salvador        33.3
189                                         San Marino        33.3
190                                            Somalia        24.4
191                                             Serbia        38.8
192         Sub-Saharan Africa (excluding high income)        24.9
193                                        South Sudan        28.5
194                                 Sub-Saharan Africa        24.9
195                                       Small states        19.9
196                              Sao Tome and Principe        23.6
197                                           Suriname        29.4
198                                    Slovak Republic        22.7
199                                           Slovenia        27.8
200                                             Sweden        47.0
201                                           Eswatini         9.6
202                                         Seychelles        24.2
203                               Syrian Arab Republic        11.2
204                                               Chad        15.4
205         East Asia & Pacific (IDA & IBRD countries)        21.9
206       Europe & Central Asia (IDA & IBRD countries)        24.4
207                                               Togo        18.7
208                                           Thailand        15.7
209                                         Tajikistan        23.8
210                                       Turkmenistan        25.0
211  Latin America & the Caribbean (IDA & IBRD coun...        29.5
212                                        Timor-Leste        38.5
213  Middle East & North Africa (IDA & IBRD countries)        18.4
214                                              Tonga         7.4
215                            South Asia (IDA & IBRD)        18.9
216          Sub-Saharan Africa (IDA & IBRD countries)        24.9
217                                Trinidad and Tobago        26.2
218                                            Tunisia        24.9
219                                             Turkey        17.3
220                                             Tuvalu         6.3
221                                           Tanzania        36.7
222                                             Uganda        34.9
223                                            Ukraine        20.8
224                                Upper middle income        26.5
225                                            Uruguay        21.2
226                                      United States        27.5
227                                         Uzbekistan        32.0
228                     St. Vincent and the Grenadines        18.2
229                                      Venezuela, RB        22.2
230                                            Vietnam        26.7
231                                            Vanuatu         0.0
232                                              World        25.6
233                                              Samoa        10.0
234                                        Yemen, Rep.         0.3
235                                       South Africa        46.8
236                                             Zambia        16.8
237                                           Zimbabwe        31.9